ALTER TABLE "Portfolio"
  ALTER COLUMN "amount" TYPE DECIMAL(36,18) USING "amount"::DECIMAL(36,18),
  ALTER COLUMN "buyPrice" TYPE DECIMAL(36,18) USING "buyPrice"::DECIMAL(36,18);

ALTER TABLE "PriceAlert"
  ALTER COLUMN "targetPrice" TYPE DECIMAL(36,18) USING "targetPrice"::DECIMAL(36,18);

ALTER TABLE "InvestmentGoal"
  ALTER COLUMN "targetAmount" TYPE DECIMAL(36,18) USING "targetAmount"::DECIMAL(36,18),
  ALTER COLUMN "currentAmount" TYPE DECIMAL(36,18) USING "currentAmount"::DECIMAL(36,18);

ALTER TABLE "CryptoPriceHistory"
  ALTER COLUMN "priceUsd" TYPE DECIMAL(36,18) USING "priceUsd"::DECIMAL(36,18),
  ALTER COLUMN "marketCap" TYPE DECIMAL(36,18) USING "marketCap"::DECIMAL(36,18),
  ALTER COLUMN "volume24h" TYPE DECIMAL(36,18) USING "volume24h"::DECIMAL(36,18),
  ALTER COLUMN "change24h" TYPE DECIMAL(36,18) USING "change24h"::DECIMAL(36,18);
